[project]
name = "docs"
version = "0.1.0"
description = "Orthohmm docs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pygments>=2.18.0",
    "sphinx-rtd-theme>=3.0.2",
    "sphinx>=7.4.7",
]

[dependency-groups]
dev = [
    "sphinx-autobuild>=2024.10.3",
]
