name: CI
on: push
jobs:
  test-fast:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # make orthohmm CLI available for tests 
        make install
        # install deps for tests
        pip install pytest
        pip install pytest-cov
    - name: Install HMMER
      run: |
        brew install hmmer
    - name: Install MCL
      run: |
        mkdir installmcl
        cd installmcl
        wget https://raw.githubusercontent.com/micans/mcl/main/install-this-mcl.sh -o install-this-mcl
        chmod u+x install-this-mcl.sh
        ./install-this-mcl.sh
        PATH=$PATH:$HOME/local/bin
        mcl --version
        cd ..
    - name: Run tests
      run: |
        PATH=$PATH:$HOME/local/bin
        make test.fast
  test-full:
    runs-on: macos-latest
    env:
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # make orthohmm CLI available for tests 
        make install
        # install test dependencies
        pip install pytest
        pip install pytest-cov
    - name: Install HMMER
      run: |
        brew install hmmer
    - name: Install MCL
      run: |
        mkdir installmcl
        cd installmcl
        wget https://raw.githubusercontent.com/micans/mcl/main/install-this-mcl.sh -o install-this-mcl
        chmod u+x install-this-mcl.sh
        ./install-this-mcl.sh
        PATH=$PATH:$HOME/local/bin
        mcl --version
        cd ..
    - name: Generate coverage report
      run: |
        PATH=$PATH:$HOME/local/bin
        make test.coverage
    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./unit.coverage.xml
        flags: unit
        env_vars: PYTHON
        name: codecov-unit
        fail_ci_if_error: false
    - name: Upload integration test coverage to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./integration.coverage.xml
        flags: integration
        env_vars: PYTHON
        name: codecov-integration
        fail_ci_if_error: false
  docs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd docs
          pip install -r requirements_docs.txt
          cd ..
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Build docs
        run: |
          cd docs
          pipenv install
          pipenv run make html
          cd ..
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
